### ISSUE TITLE
exit code 1 error caused by mod conflict with CreateArmoredCopperBacktanks

### ISSUE THREAD

**Issue by green8751** [StacheGamer1609/CreateFoodAddon#3]
i linked it to this mod vai disabling all mods that weren't in an older copy of the pack i have (after making sure all mods were up to date in both versions) and turning them back on one at a time. this is the only mod that gave a exit code 1 error when i try to launch it.

no crash log was generated, but an installation with only your mod added did not crash.

added all the create related mods i had installed in the core pack, and same crash happened. conflict cause confirmed.

disabled mods one at a time, testing for a crash before moving on to the next mod so only 1 was disabled at a time, crash only stopped when mod CreateArmoredCopperBacktanks was disabled. tested with last mod to ensure this was the only other removable mod to fix the issue.

i honestly expected it to be one of the food mods, this is odd.
only noticed now that i made the list that you made both conflicting mods. i suspect something got reused that broke something critical from one or both mods.
restricted it to only your 2 mods, (other than API and create) and the same exit code 1 happened.

API:
Architectury API (Fabric/Forge)            shedaniel              architectury-4.5.76-forge.jar
Flywheel                                               jozufozu                flywheel-forge-1.18-0.6.4.jar

core mod:
Create                                                   simibubi               create-mc1.18.2_v0.5.0c.jar

conflicting mods:
CreateArmoredCopperBacktanks         StacheSebastian   createab-1.18.2_v0.2.jar
CreateFoodAdditions                           StacheSebastian    createfa-1.18.2_v1.0.9.jar

other mods:
Create Cafe                                           1mphuls3              createcafe-1.4-1.18.2.jar
Create Chunkloading                            embeddedt           createchunkloading-1.2.0-forge.jar
Create Confectionery                            Furti_Two              create-confectionery1.18.2_v1.0.8.jar
Create Deco                                          talrey                     createdeco-1.2.8-1.18.2.jar
Create: Alloyed                                     MythrilBagels        alloyed-1.18.2-v1.4b.jar
Create: Broken Bad                               jetpacker06           createbb-1.18.2-1.4.1.jar
Create: Factory                                     antop90fr              create-factory-1.18.2-v1.6.jar
Industrialized Create                            coppertj                 industrializedcreate1.18.2_1.2.1.jar

**Comment by StacheSebastian** [comment]
Thank you very much for reporting the problem!
I found the problem and I'll fix it soon.
